Fix path for check log
sensu-plugins/sensu-plugins-logs pull request #22
Opened 2017-04-28 21:33 UTC by mf69

## Pull Request Checklist

**Is this in reference to an existing issue?**
Yes Plugin copies the file to /var/cache folder and does its checking #15

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatablity Issues

2017-05-12 20:32 UTC, majormoses commented on bin/check-log.rb
> +  BASE_DIR = '/var/cache/sensu/check-log'.freeze
Is there a reason to not make this an option and default to this? I tend to dislike configuration that is not exposed.

2017-05-21 19:07 UTC, majormoses commented
I tried running this check and I feel more strongly about it being an option I had no choice but to create the dir it wanted and chowned it. This is not a good experience and the user should be able to specify any dir they want as the base dir.

2017-05-21 19:08 UTC, majormoses requested changes
Remove `BASE_DIR` constant and make it an an option with a sane default.

2017-06-02 04:05 UTC, majormoses commented
@mf69 any chance of picking this back up?

2017-06-26 17:48 UTC, mf69 commented
I don't really grok what you are asking for.  Perhaps provide an example from another sensu-plugin that works the way you specified?

2017-06-26 17:57 UTC, majormoses commented
Remove this line: `BASE_DIR = '/var/cache/check-log'.freeze` and make an option that can have your proposed path as a default and be overwritten at runtime to provide more flexibility like.

2017-07-20 01:31 UTC, majormoses commented
When I have some time I will do this right now I am closing this because of lack of activity and is the wrong approach to solve this.

2017-07-20 01:31 UTC, closed without merging