Add 'return-error-limit' option to limit the number of returned matched lines\log entries
sensu-plugins/sensu-plugins-logs pull request #29
Opened 2017-07-18 22:53 UTC by jhshadi

## Pull Request Checklist

**Is this in reference to an existing issue?**
#28 

#### General

- [ x ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [  ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
limit the number of returned matched lines\log entries.

#### Known Compatibility Issues

2017-07-18 23:39 UTC, majormoses requested changes
Overall looks good, I need some verification of a few things:
- git ownership of commits asking for credit
- testing artifact: this can be a unit test or a gist/screenshot of the input and output to make sure it works as intended.

2017-07-18 23:39 UTC, majormoses commented on CHANGELOG.md
> +- Add `return-length` option to support custom length for returned matched lines (@jhshadi)
are you shlomi? https://github.com/sensu-plugins/sensu-plugins-logs/compare/1.0.0...1.1.0 could you please confirm something that we can verify to give you credit?

2017-07-18 23:39 UTC, majormoses commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
are you shlomi? https://github.com/sensu-plugins/sensu-plugins-logs/compare/1.0.0...1.1.0 could you please confirm something that we can verify to give you credit?

2017-07-18 23:39 UTC, majormoses commented on bin/check-log.rb
> +         description: 'Max number of returned matched lines\log entries',
if you want to call out log entries then put it on parenthesis they are not equivalent. Not all logs always are single lines.

2017-07-18 23:45 UTC, jhshadi commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
@majormoses sure, what\how to confirm it?

2017-07-18 23:55 UTC, jhshadi commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
@majormoses I have tested it locally but i can add a unit test.
Can you reference to an example test and will take it from there?

2017-07-18 23:58 UTC, majormoses commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
do you still have access to this email? shlomi@innovid.com

2017-07-18 23:59 UTC, jhshadi commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
@majormoses yes, i do have access to shlomi@innovid.com.

2017-07-19 00:01 UTC, majormoses commented
regarding testing just running the command locally and capturing the input and output in a gist is enough, something like this: https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/16

2017-07-19 00:08 UTC, majormoses commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
I will send you an email and have you confirm that is enough for me.

You will need to reply back with the following: "I really need to setup github with the email address outlined here: https://help.github.com/articles/setting-your-commit-email-address-on-github/"

2017-07-19 00:18 UTC, majormoses commented on CHANGELOG.md
> +- Add `log-pattern` option to support read and match against whole log entry instead of single line (@jhshadi)
confirmed.

2017-07-19 00:31 UTC, majormoses requested changes

2017-07-19 00:31 UTC, majormoses commented on CHANGELOG.md
> +- Add `return-error-limit` option to limit the number of returned matched lines\"log entries" (@jhshadi)
either actually use parenthesis or change the commit message to match whats being changed here...

2017-08-12 23:33 UTC, majormoses commented
@jhshadi any plans to pick this back up?

2017-09-09 18:49 UTC, majormoses commented
closing due to inactivity

2017-09-17 09:00 UTC, jhshadi commented
@majormoses sorry for the long absent, can you reopen the pull request?

2017-09-21 13:40 UTC, jhshadi commented
@majormoses accidentally reverted the change and then apply it back. sorry for the hustle :)
in any case run the command with the `--return-error-limit` feature:
```bash
Shlomis-MBP:sensu-plugins-logs shlomi$ ./bin/check-log.rb --log-file test/logs/example_01.log --state-dir ./test/logs/state --pattern error --crit 1 --return-error-limit 1 --return
CheckLog CRITICAL: 0 warnings, 2 criticals for pattern error. 
this is error line
```
tried adding unit tests using the reference you linked above but couldn't make them run properly. will try adding those later on.

LMK if there's anything else is needed.

2017-09-23 21:55 UTC, jhshadi commented
@majormoses any other changes needed here?

2017-09-23 22:03 UTC, majormoses commented
sorry thought I got back to this one. Let me review and will report back shortly.

2017-09-23 22:06 UTC, majormoses approved these changes

2017-09-23 22:06 UTC, merged

2017-09-23 22:13 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.3.0