Option descriptions
sensu-plugins/sensu-plugins-logs pull request #33
Opened 2018-03-13 19:10 UTC by cgeers

## Pull Request Checklist

**Is this in reference to an existing issue?**
#13 
#### General

- [/] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [ ] RuboCop passes

- [/] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatibility Issues

2018-03-15 03:47 UTC, majormoses requested changes
Thanks for finding and fixing this, I think we need one more tweak before calling this a solved issue.

2018-03-15 03:47 UTC, majormoses commented on bin/check-log.rb
> +         description: 'Warning level if pattern is found >= N times',
If this is true then we should probably make it a default of `1` as no default will eval to `nil` when calling `.to_i` it becomes `0` so it should either be a default of 1 or remove the greater equality for a greater than.
```
$ irb
irb(main):001:0> nil.to_i
=> 0
```

2018-03-15 03:47 UTC, majormoses commented on bin/check-log.rb
> +         description: 'Critical level if pattern is found >= N times',
If this is true then we should probably make it a default of `1` as no default will eval to `nil` when calling `.to_i` it becomes `0` so it should either be a default of 1 or remove the greater equality for a greater than.
```
$ irb
irb(main):001:0> nil.to_i
=> 0
```

2018-03-15 03:48 UTC, majormoses commented
Can you please include and automated or manual [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts)?

2018-03-29 22:30 UTC, cgeers commented
I opted to revert the original behavior of defaulting to the critical severity if any matches are found. 

I've included an integration test covering basic behavior of the check-log.rb check.  I'm not quite sure why the travis build is failing though.  I must have missed something.

2018-03-29 23:43 UTC, majormoses approved these changes

2018-03-29 23:44 UTC, merged

2018-03-29 23:56 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.3.2