Update to require sensu-plugin 2.7
sensu-plugins/sensu-plugins-logs pull request #34
Opened 2018-09-22 21:57 UTC by jspaleta

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [X] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Update the gemspec to use sensu-plugin  2.7 which includes the logic to map sensu 2 events into sensu 1.5 events for handlers and mutators based on the sensu-plugin Handler and Mutator classes.

#### Known Compatibility Issues

2018-09-22 23:00 UTC, jspaleta commented
no idea why travis builds are failing. the errors are assocatied with kitchen.. so it seams like some sort of travis specific breakage.. not something in the commit.

2018-09-23 00:37 UTC, majormoses commented
In the [logs](https://travis-ci.org/sensu-plugins/sensu-plugins-logs/jobs/431983839#L1548) it indicates that `net-telnet` version `0.2.0` dropped ruby support for < 2.3 in https://github.com/ruby/net-telnet/commit/4b5432a1d4f81e6c56bac6e72b0fe27bb8a6dfd8#diff-de0020d29d91153b0fe757ca69118a4e I am looking into what needs to be fixed, might be fastest/easiest to just drop those older versions support, let me get back to you on that one.

2018-09-25 02:10 UTC, majormoses commented
Re-running tests as we should now be pinned properly if we pull in `specinfra` version `v2.76.2`

2018-09-25 02:20 UTC, majormoses commented
@jspaleta I got one of the tests to pass now its just ruby 2.1 I am pretty sure that this can be temp worked around by adding this to the gemspec:
```
s.add_runtime_dependency 'net-ssh', '~> 4.0'
```

2018-09-30 23:26 UTC, majormoses approved these changes

2018-09-30 23:26 UTC, majormoses commented on CHANGELOG.md
> +### Changed
This needs to be a `### Breaking Changes` header but I can fix that for you.

2018-09-30 23:28 UTC, majormoses requested changes
We need to update https://github.com/sensu-plugins/sensu-plugins-logs/blob/9fc70a68103048893d18a2c1ba99c1408fa12298/.travis.yml#L12-L13 as well.

2018-10-01 01:04 UTC, jspaleta commented
Okay made the change in supported ruby versions a breaking change, and bumped major version accordingly.  Let me know if there's anything else.

2018-10-01 02:23 UTC, majormoses approved these changes

2018-10-01 02:23 UTC, majormoses commented on lib/sensu-plugins-logs/version.rb
> +    MAJOR = 2
its ok in this case but in general we do the actual versioning post acceptance.

2018-10-01 02:24 UTC, merged

2018-10-01 02:36 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-logs/versions/2.0.0